### Containerfile notes 


FROM docker.io/library/ubuntu:24.04

# OCI Annotations from https://github.com/opencontainers/image-spec/blob/master/annotations.md

LABEL \
org.opencontainers.image.url="TBD"  \
org.opencontainers.image.title="Zabbix proxy and WAN connector"          \
org.opencontainers.image.description="Don't forget to mount persistent storage to DATA_DIR, otherwise you will loose data! In order to prevent it, the container refuses to start if it suspects that DATA_DIR is not provided with external persistent storage."


# ARG is gone after build
# ENV will be in the image

ENV TZ="Europe/Brussels"
ENV DATA_DIR="/mnt/zabbix-wan-connector"
ENV INSTALL_DIR="/root/scripts"

ENV ZBX_HOSTNAME="My dummy Zabbix proxy"
# 0 - active mode, 1 - passive mode
ENV ZBX_PROXYMODE="0"
ENV ZBX_SERVER_HOST="dummy-zabbix.lan"
ENV ZBX_TIMEOUT=10
ENV ZBX_DEBUGLEVEL=3
ENV ZBX_PROXYCONFIGFREQUENCY=3600
ENV ZBX_DATASENDERFREQUENCY=1
ENV ZBX_ENABLEREMOTECOMMANDS=1
ENV ZBX_LOGREMOTECOMMANDS=1
ENV ZBX_STATSALLOWEDIP="127.0.0.1,::1,dummy-zabbix.lan"
ENV X_ZBX_SOURCEIP="Set ZBX_SOURCEIP to a value if you need to specify the outgoing address"

# Source: https://www.zabbix.com/download?zabbix=7.2&os_distribution=ubuntu&os_version=24.04&components=proxy&db=sqlite3&ws=
ARG X_ZABBIX_REPO_URL="https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/"
ARG X_ZABBIX_REPO_PKG="zabbix-release_latest_7.4+ubuntu24.04_all.deb"

ARG RUNTIME_PKGS=" \
            tzdata \
            tini \
            nano \
            openssh-client \
            openvpn \
            fping \
            iproute2 \
            "

ARG BUILD_PKGS=" \
            wget \
            "

# Build and cleanup needs to stay in the same RUN
# otherwise cleanup will run in a separate layer and wont reduce the image size
RUN set -eux && \
    echo "path-include=/usr/share/doc/zabbix-sql-scripts/sqlite3/*" >> /etc/dpkg/dpkg.cfg.d/excludes && \
    export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && \
    echo 'tzdata tzdata/Areas select Europe' >> /debconf-preseed.txt && \
    echo 'tzdata tzdata/Zones/Europe select Brussels' >> /debconf-preseed.txt && \
    debconf-set-selections /debconf-preseed.txt && \
    echo "Installing packages..." && \
    apt update &&\
    apt install -y \
        ${RUNTIME_PKGS} \
        ${BUILD_PKGS} && \
    wget "${X_ZABBIX_REPO_URL}/${X_ZABBIX_REPO_PKG}" && \
    dpkg -i ${X_ZABBIX_REPO_PKG} && \
    apt update &&\
    apt install -y  zabbix-proxy-sqlite3 zabbix-sql-scripts && \
    mkdir -p "${INSTALL_DIR}" && \
    mkdir -p "${DATA_DIR}" && \
    touch "${DATA_DIR}/NO_PERMANENT_STORAGE" && \
    echo "Removing build-only dependencies..." && \
    apt remove \
        -y \
        --purge \
        ${BUILD_PKGS} && \
    rm -rf /var/cache/apt/* && \
    rm -rf /root/.cache && \
    rm ${X_ZABBIX_REPO_PKG} && \
    rm /debconf-preseed.txt  && \
    echo "Cleanup done, finishing build..."

COPY start-connection.sh "${INSTALL_DIR}/start-connection.sh"
COPY start-netcat.sh     "${INSTALL_DIR}/start-netcat.sh"

COPY entrypoint.sh /entrypoint.sh


VOLUME [ "${DATA_DIR}" ]

# CMD can be overridden in "podman run", ENTRYPOINT can't be

# Also if you specify both, in normal format it wont work, 
# in array format CMD definition will become argument after ENTRYPOINT
ENTRYPOINT ["/usr/bin/tini", "--", "/entrypoint.sh"]
